In [2]:
import numpy as np

In [3]:
## Creating Numpy Array

#create a 1D array

arr1 = np.array([1,2,3,4,5]) 
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = arr1

print(arr2)


[1 2 3 4 5]


In [5]:
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
arr2.reshape(5,1) #5 rows and 1 column

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
#create a 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
# create an array with a range of values
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# create an array with a range of values and reshape it
np.arange(0,11,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [10]:
# create an array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
# create an array of ones with a specified shape
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
## identity array/diagonal matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# Array attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: ",arr)
print("Array shape: ",arr.shape)
print("Array size: ",arr.size)
print("Array dimension: ",arr.ndim)
print("Array data type: ",arr.dtype)
print("Item size: ",arr.itemsize)

Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape:  (3, 3)
Array size:  9
Array dimension:  2
Array data type:  int64
Item size:  8


In [14]:
## Vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition: ",arr1+arr2)

## Element wise subtraction
print("Subtraction: ",arr1-arr2)

## Element wise multiplication
print("Multiplication: ",arr1*arr2)     

## Element wise division
print("Division: ",arr1/arr2)

## Element wise power
print("Power: ",arr1**arr2)


Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]
Power:  [                   1              1048576      205891132094649
                    0 -6776596920136667815]


In [15]:
## Universal functions

arr = np.array([2,3,4,5,6])

## Square root
print("Square root:",np.sqrt(arr))

## Exponential
print("Exponential: ",np.exp(arr))

## Sine
print("Sine: ",np.sin(arr))

## natural logarithm
print("Natural logarithm: ",np.log(arr))

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural logarithm:  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
## Slicing operations/ indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr.shape)
print("First Row:", arr[0])
print("Second Row:", arr[1])
print("Third Row:", arr[2])

#find 11

print(arr[2,2])
print(arr[2][2])


#find 7,8,11,12

print(arr[1:,2:])

#find 3,4,7,8

print(arr[0:2,2:])

#find 6 7 10 11
print("---------------")
print(arr[1:3,1:3])

(3, 4)
First Row: [1 2 3 4]
Second Row: [5 6 7 8]
Third Row: [ 9 10 11 12]
11
11
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
---------------
[[ 6  7]
 [10 11]]


In [20]:
##Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [25]:
arr[1:] = 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [26]:
## statistical concept -- Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])
mean = np.mean(data)
print("Mean: ",mean)
std = np.std(data)
print("Standard Deviation: ",std)

normalized_data = (data-mean)/std

print("Normalized data: ",normalized_data)

Mean:  3.0
Standard Deviation:  1.4142135623730951
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [28]:
#Mean 
mean = np.mean(data)

#median
median = np.median(data)

#Standard Deviation
std = np.std(data)

#variance
var = np.var(data)  

print("Mean: ",mean)
print("Median: ",median)
print("Standard Deviation: ",std)
print("Variance: ",var)

Mean:  3.0
Median:  3.0
Standard Deviation:  1.4142135623730951
Variance:  2.0


In [36]:
## Logical operations

data =np.array([1,2,3,4,5,6,7,8,9,10])

#greater than 5
print(data>5)

# to get the values greater than 5
data[data>5]

# Get data > 5 and <8
# and(&) or(|)
print(data[(data>5) & (data<8)])
print(data[(data>5) | (data<8)])

[False False False False False  True  True  True  True  True]
[6 7]
[ 1  2  3  4  5  6  7  8  9 10]
